### ISSUE TITLE
INSTALL Missing

### ISSUE THREAD

**Issue by jzb** [purpleidea/vagrant-builder#4]
The README references an INSTALL file, but it doesn't exist. (And the link referenced does not exist: https://github.com/purpleidea/vagrant-builder/blob/master/INSTALL).

**Comment by purpleidea** [comment]
@jzb Good catch, thanks.

This is my fault for using existing project templates when I kicked this together!

**Comment by purpleidea** [comment]
Looks like @jzb has a nice PR in https://github.com/purpleidea/vagrant-builder/pull/5 ...

**Comment by purpleidea** [comment]
Fixed :)
